version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./Data:/app/Data
      - ./views:/app/views
      - ./utils:/app/utils
    environment:
      - STREAMLIT_ENV=production

  airflow:
    image: apache/airflow:latest
    environment:
      - AIRFLOW__WEBSERVER__RBAC=True
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.contrib.auth.backends.password_auth
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./Data:/app/Data
    ports:
      - "8080:8080"
    command: ["standalone"]
    restart: always